# Generated by Django 4.0.3 on 2022-04-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='author',
            new_name='owner',
        ),
    ]
