# Generated by Django 4.0.3 on 2022-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0002_rename_created_mealplan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(),
        ),
    ]
