# Generated by Django 4.0.3 on 2022-04-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created',
            new_name='date',
        ),
    ]
