# Generated by Django 4.0.3 on 2022-05-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_shoppingitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
